"""Update User model: add active with server_default

Revision ID: 39e171789970
Revises: e3157ef92665
Create Date: 2025-03-10 23:58:46.092041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39e171789970'
down_revision = 'e3157ef92665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')
        batch_op.drop_column('cost_center')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_center', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), nullable=True))

    # ### end Alembic commands ###
