"""Add force_password_reset column to User model

Revision ID: 61bbd02a2917
Revises: 97aecd46a1e0
Create Date: 2025-03-11 15:40:53.755017

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '61bbd02a2917'
down_revision = '97aecd46a1e0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'force_password_reset',
                sa.Boolean(),
                nullable=False,
                server_default='0'  # Ensures existing rows default to False
            )
        )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('force_password_reset')
    # ### end Alembic commands ###
