"""Add name and cost_center fields to User model

Revision ID: 97aecd46a1e0
Revises: 39e171789970
Create Date: 2025-03-11 00:07:20.579879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97aecd46a1e0'
down_revision = '39e171789970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cost_center', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cost_center')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
