"""Add name and cost_center to User model

Revision ID: e3157ef92665
Revises: ba580bc21dec
Create Date: 2025-03-10 21:28:03.072976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3157ef92665'
down_revision = 'ba580bc21dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('cost_center', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cost_center')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
